In [10]:
import numpy as np 
arr = np.array([1,2,3,4,5])
result = []
for num in arr:
    result.append(int(num**2))
print(result)    

[1, 4, 9, 16, 25]


In [12]:
import numpy as np #sometime we need to write less line of code to save memory
arr = np.array([1,2,3,4,5])
result = [int(num**2) for num in arr]
print(result)

[1, 4, 9, 16, 25]


In [13]:
import numpy as np #Vectorisation in numpy it also saves memory and perform  calculation fast in numpy
arr = np.array([1,2,3,4,5])
result = arr**2
print(result)

[ 1  4  9 16 25]


In [17]:
#Broadcasting in numpy
import numpy as np
arr1 = np.array([1,2,3,4,5])
result = arr1 + 10
print(result)

[11 12 13 14 15]


In [21]:
import numpy as np 
arr2 = np.array([1,2,3,4,5])
arr3 = np.array([6,7,8,9,10])
result = arr2 + arr3 
print(result)

[ 7  9 11 13 15]


In [23]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # broadcasting in 2d array
arr2 = np.array([1, 2, 3])

In [25]:
result = arr1 + arr2
result

array([[2, 4, 6],
       [5, 7, 9]])

In [27]:
#applying broadcasting on real world scenarios in numerical calculation

# Simulating a dataset (5 samples, 3 features)
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
