In [1]:
import numpy as np 

In [2]:
!pip install numpy


In [4]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
np.full((3,4),4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [11]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [13]:
myarr = np.array([[2,3,4],[4,5,6],[7,8,9],[2,4,6]])

In [14]:
myarr

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9],
       [2, 4, 6]])

In [15]:
myarr.shape

(4, 3)

In [16]:
myarr.size

12

In [17]:
myarr.ndim

2

In [18]:
myarr.dtype

dtype('int64')

In [19]:
myarr = np.array([[2,3,4],[4,5,6],[7,8,9],[2,4,6]],'float32')

In [20]:
myarr

array([[2., 3., 4.],
       [4., 5., 6.],
       [7., 8., 9.],
       [2., 4., 6.]], dtype=float32)

In [24]:
 n = myarr.astype('float64')

In [25]:
n

array([[2., 3., 4.],
       [4., 5., 6.],
       [7., 8., 9.],
       [2., 4., 6.]])

In [26]:
myarr.dtype

dtype('float32')

In [27]:
n.dtype

dtype('float64')

In [30]:
myarr = np.array([[2,3,4],[4,5,6],[7,8,9],[2,4,6]],'float32')

In [31]:
myarr

array([[2., 3., 4.],
       [4., 5., 6.],
       [7., 8., 9.],
       [2., 4., 6.]], dtype=float32)

In [32]:
myarr.shape


(4, 3)

In [34]:
myarr.reshape((3,4))

array([[2., 3., 4., 4.],
       [5., 6., 7., 8.],
       [9., 2., 4., 6.]], dtype=float32)

In [35]:
myarr.flatten()

array([2., 3., 4., 4., 5., 6., 7., 8., 9., 2., 4., 6.], dtype=float32)