In [1]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])

In [2]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
n = arr.flatten()

In [4]:
n

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
n[5]

np.int64(6)

In [6]:
n[0:3]

array([1, 2, 3])

In [7]:
n[:6]

array([1, 2, 3, 4, 5, 6])

In [8]:
n[4:]

array([5, 6, 7, 8])

# slicing and show how slicing in numpy present view of arr bot make copy of it to save memory

In [9]:
b = n[2:6]

In [10]:
b

array([3, 4, 5, 6])

In [11]:
b[3] = 344

In [12]:
b

array([  3,   4,   5, 344])

In [13]:
n

array([  1,   2,   3,   4,   5, 344,   7,   8])

# here we see if we need to make copy of array in array instead of making it only view 


In [14]:
b = n[2:6].copy()

In [15]:
b[3] = 3442321

In [16]:
b

array([      3,       4,       5, 3442321])

In [17]:
n

array([  1,   2,   3,   4,   5, 344,   7,   8])

# fancy indexing

In [28]:
import numpy as np
arr1 = np.array([20,30,40,50,60])

In [31]:
idx = [2,4]

In [33]:
arr1[idx]

array([40, 60])

In [32]:
# print(arr1[idx])

[40 60]


In [34]:
arr1 = np.array([20,30,40,50,60])


In [35]:
mask = arr1>30

In [36]:
mask

array([False, False,  True,  True,  True])