# indexing and accessing 1d and 2d array

In [1]:
import numpy as np
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

In [2]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[1]

array([4, 5, 6])

In [4]:
arr[1,0]

np.int64(4)

In [5]:
print(np.sum(arr, axis= 0))

[12 15 18]


In [6]:
print(np.sum(arr,axis =1))

[ 6 15 24]


In [7]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6], 
                [7, 8, 9], 
                [1, 2, 3]])

In [8]:
arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [9]:
arr[2:3,0:2]

array([[7, 8]])

# Indexing and accessing of multidimensional array


In [10]:
arr3D = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                  [[7, 8, 9],
                   [10,11,12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [11]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

print(arr3D[:, 0, :])   # Get the first row from both sheets

6
[[1 2 3]
 [7 8 9]]


In [12]:
# Get all rows of the first column
first_col = arr[:, 0]
print(first_col)  # Output: [1 4 7]

[1 4 7 1]


# Changing data along an axis


In [13]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)

[[1 0 3]
 [4 0 6]
 [7 0 9]
 [1 0 3]]
