In [1]:
import numpy as np
arr = np.array([23,45,37,89])

In [2]:
arr

array([23, 45, 37, 89])

In [3]:
arr.dtype

dtype('int64')

In [4]:
import numpy as np
arr2 = np.array([23,45,37,89],"int32")

In [5]:
arr2

array([23, 45, 37, 89], dtype=int32)

In [6]:
arr2.dtype

dtype('int32')

In [7]:
arr.nbytes #to check how memory they all store 

32

In [8]:
arr2.nbytes

16

In [9]:
arr3 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128') 
print(arr)

[23 45 37 89]


In [10]:
arr3.nbytes

48

In [11]:
arr4 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex64')#Downcasting
print(arr)

[23 45 37 89]


In [12]:
arr4.nbytes

24