In [1]:
import numpy as np
import time 

size = 1_00_000_00

list1 = list(range(size))
list2 = list(range(size))

start = time.time()

result = [x+y for x,y in zip(list1,list2)]
end = time.time()
print("python list addition time :", end - start)


python list addition time : 0.16525983810424805


In [2]:
import numpy as np 
import time 

size = 1_00_000_00

list1 = list(range(size))
list2 = list(range(size))

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2
end = time.time()

print("python numpy addition time :" , end - start)

python numpy addition time : 0.06171703338623047


# CREATING NUMPY ARRAYS


In [6]:
import numpy as np # this was use to check types of array 
array1 = np.array([1,2,3,4,5])
print(array1)
print(type(array1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
import numpy as np # this was use to check shape of array because we can create 1D,2D arrays
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
print(array2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
