In [52]:
array = np.full((4,3),3)
print(array.shape)

(4, 3)


In [54]:
array = np.full((4,3),3,dtype ="float32")
array

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)

In [57]:
n = array.astype(dtype="int32")
n

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]], dtype=int32)

In [59]:
array = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print("Even numbers from the above list:",array[idx])

Even numbers from the above list: [2 4 6]


In [66]:
array1 = np.array([10,20,30,40,50,60,70,80,90])
print(array1)
n = array1.reshape((3,3))
print(n)

[10 20 30 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
