In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr, axis=0)) #axis 0 used for rows accessing but operations are applied on the columns
print(np.sum(arr, axis=1))#axis 1 used for columns accessing but operations are applied on the rows

[12 15 18]
[ 6 15 24]
