In [1]:
import numpy as np
arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr, axis=0)) #axis 0 used for rows accessing but operations are applied on the columns
print(np.sum(arr, axis=1))#axis 1 used for columns accessing but operations are applied on the rows

[12 15 18]
[ 6 15 24]


In [5]:
import pandas as pd 
data = {"Name":["Aman","Mohit","Raju","Priya","Sejal"],
         "Age": [20,22,19,23,25],
         "Marks":[89,98,57,99,10],}
df = pd.DataFrame(data)
df

,Name,Age,Marks
0,Aman,20,89
1,Mohit,22,98
2,Raju,19,57
3,Priya,23,99
4,Sejal,25,10


In [ ]:
import numpy as np 
arr = np.array([2,4,6])